### PR TITLE
Replace 2.6.0rc1 with 2.6.0 final

### PR DESCRIPTION
**Pull request by ihnorton**

### CODE REVIEW

**Comment by ihnorton** [comment]
Why are we using sha1 here?

**Review by bdeng-xt — COMMENTED** [review]
I changed TILEDB_DOWNLOAD_SHA1 to SHA1 value from SHA256. If there is more benefit to use SHA256, I can change all SHA1 to SHA256

**Comment by ihnorton** [comment]
Yes, we should prefer sha256 wherever possible, thanks.

**Comment by ihnorton** [comment]
For now, please just update 2.5 and use my update for 2.6

**Comment by ihnorton** [comment]
No need to update all the others right now

**Pull request merged**
