### PR TITLE
Bump version to 5.5.0.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**

### CODE REVIEW

**Review by ihnorton — APPROVED** [review]
Where do we set the pin to 2.15? Does that happen directly in nuget or ???

**Comment by teo-tsirpanis** [comment]
https://github.com/TileDB-Inc/TileDB-CSharp/blob/30f6075eb3143fd7a493978bb43d96280b46b3cd/Directory.Packages.props#L5

**Comment by teo-tsirpanis** [comment]
This file is automatically imported to all projects in the repository by MSBuild.

**Comment by ihnorton** [comment]
Got it, thanks!

**Pull request merged**
